### ISSUE TITLE
CTFd beta theme breaks 08_hook_challenge

### ISSUE THREAD

**Issue by zhuyifei1999** [sigpwny/ctfd2pages#2]
The JS is different. See https://github.com/sigpwny/ctfd2pages/pull/1#issuecomment-1349610168

**Comment by intrigus-lgtm** [comment]
> Could you clarify on why you think so? I see the block
> 
> ```js
>   if (CTFd._functions.challenge.submitChallenge) {
>     CTFd._functions.challenge.submitChallenge(challengeId, challengeValue);
>     return;
>   }
> ```
> 
> and it seems to me that it's almost like it's intended to be hooked there

My impression was that `CTFd._functions.challenge.submitChallenge` is supposed to be hooked by a theme creator.
https://github.com/CTFd/CTFd.js/blob/9aeb1b373386215a5a3d767d5c2e84051fb9938e/main.js#L78-L79. Same with `displaySubmissionResponse`.

If we just hook (as a ctfd2pages user) `CTFd.pages.challenge.submitChallenge`, this would mean that hooks defined by the theme creator would not be called.
At least that's my impression.

**Comment by zhuyifei1999** [comment]
Hmm you have a good point. I gave it a deeper look

The caller of that function is here: https://github.com/CTFd/core-beta/blob/0ed222a7d09a8010ba9ce96549ee150e72c3cfaf/assets/js/challenges.js#L126-L133
```js
  async submitChallenge() {
    this.response = await CTFd.pages.challenge.submitChallenge(
      this.id,
      this.submission
    );

    await this.renderSubmissionResponse();
  },
```

There's a separation of "calling the API" vs "rendering the response". For a theme, I think changing "rendering the response" is probable, but I'm not sure why a theme would override "calling the API" part. Perhaps the API might be located at a different location, or they want to add additional parameters / pre-process the response in some way, or add some sort of "submission counter" but do it client side for some reason?

I'm also not sure why displaySubmissionResponse is there. It seems like a callback where the response gets rendered after it's submitted, but usually one could just use the return value instead. It's also not used in core-beta AFAICT.

Looking at the code where it loads hints: https://github.com/CTFd/CTFd.js/blob/9aeb1b373386215a5a3d767d5c2e84051fb9938e/pages/challenge.js#L60-L66
```js
export async function loadHint(hintId) {
  const response = await CTFd.fetch(`/api/v1/hints/${hintId}`, {
    method: "GET",
  });

  return await response.json(); // hint
}
```

It looks so much simpler, and... without hooking points. 

I also looked into how `CTFd._functions.challenge` is being used in core-beta, if it sets any hooks. Nope, it's only used once and it's not hooking: https://github.com/CTFd/core-beta/search?q=CTFd._functions.challenge Though to be honest, since `CTFd._functions.challenge.displayUnlockError` calls `alert` it's likely that core-beta is gonna move away from using that function.

I think I prefer hooking an API function rather than hooking the fetch function because by the time of fetch, the request is kinda of "serialized" already; you have to be responsible for testing the URL, de-serializing the body, and serializing the response into JSON that will be de-serialized immediately after. So I think I'd override `CTFd.pages.challenge.submitChallenge` and `CTFd.pages.challenge.loadHint` directly without even bothering with `CTFd._functions.challenge.submitChallenge`.

An analogy in C systems programming would be to hook library calls vs somehow hooking the `syscall` instruction. Say, you want to change thread creation mechanics of `pthread_create`. Instead of overriding `pthread_create` symbol, you hook on the syscall instruction and check if the syscall number is NR_clone and then read the arguments from registers (not to mention a libc could in theory switch to using clone3 syscall instead anytime). I wouldn't say it's wrong to do that, but it feels odd, unless the use case is like building a VM where you'd want to hook every syscall anyways, if you get what I mean.

I also want to see if there's a way to detect if a CTF site is using a theme based on the old theme or the beta theme, so I won't have to bundle both implementations in the same script. Hmph.

**Comment by zhuyifei1999** [comment]
I think this will work:

```diff
diff --git a/08_hook_challenge/webpack-index.js b/08_hook_challenge/webpack-index.js
index f493755..28be05a 100644
--- a/08_hook_challenge/webpack-index.js
+++ b/08_hook_challenge/webpack-index.js
@@ -1,7 +1,20 @@
 /* global CTFd */
 
 const FLAGS = require('./flags.json');
-const md = CTFd.lib.markdown();
+const MarkdownIt = require('markdown-it');
+
+// source: https://github.com/CTFd/CTFd.js/commit/2c0db5b355dad9ebfdeb6dea66df0633c4946b94
+const markdown = function(config) {
+  const mdConfig = {...{html: true, linkify: true}, ...config};
+  const md = new MarkdownIt(mdConfig);
+  md.renderer.rules.link_open = function(tokens, idx, options, env, self) {
+    tokens[idx].attrPush(['target', '_blank']);
+    return self.renderToken(tokens, idx, options);
+  };
+  return md;
+};
+
+const md = markdown();
 
 const sha256sum = async (string) => {
   const utf8 = new TextEncoder().encode(string);
@@ -11,8 +24,7 @@ const sha256sum = async (string) => {
       .join('');
 };
 
-CTFd.api.post_challenge_attempt = async function(parameters, body) {
-  const {challenge_id: chalId, submission: flag} = body;
+CTFd.pages.challenge.submitChallenge = async function(chalId, flag) {
   const expectedSHA = FLAGS[chalId];
   const submittedSHA = await sha256sum(flag);
 
@@ -46,9 +58,7 @@ CTFd.api.post_challenge_attempt = async function(parameters, body) {
   }
 };
 
-CTFd.api.get_hint = async function(parameters) {
-  const hintId = parameters.hintId;
-
+CTFd.pages.challenge.loadHint = async function(hintId) {
   for (const hintOrig of CTFd._internal.challenge.data.hints) {
     if (hintOrig.id !== hintId) {
       continue;
```

I just need to 
1. build a test CTFd site to test this on
2. figure out how to bundle markdown
3. support both base themes

Btw intrigus, would you want your CTF to be listed under https://github.com/sigpwny/ctfd2pages#examples ?

**Comment by zhuyifei1999** [comment]
> I just need to [...]

All done. How does this look? https://github.com/sigpwny/ctfd2pages/commit/076e9dfc24b95837d92bb9b2212e9f6f714b5ae8

**Comment by intrigus-lgtm** [comment]
> Btw intrigus, would you want your CTF to be listed under https://github.com/sigpwny/ctfd2pages#examples ?

Yes, please add https://2022.ctf.kitctf.de to the list

> All done. How does this look? https://github.com/sigpwny/ctfd2pages/commit/076e9dfc24b95837d92bb9b2212e9f6f714b5ae8

Works fine. A bit unfortunate that you have to bundle markdown now even if you're not having any hints, but optimizing this is probably not worth it :D
